// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRmJBir_Bkod0JGqhkJYws6a4OUt4G1nc',
    appId: '1:936437867273:web:53f3f30c4931fa0b3b29d8',
    messagingSenderId: '936437867273',
    projectId: 'skillmatch-8a9c0',
    authDomain: 'skillmatch-8a9c0.firebaseapp.com',
    databaseURL: 'https://skillmatch-8a9c0-default-rtdb.firebaseio.com',
    storageBucket: 'skillmatch-8a9c0.firebasestorage.app',
    measurementId: 'G-9GXRMJ637C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNac5sosReD8Sq1ivtUDJNcr0pTyAo84',
    appId: '1:936437867273:android:d48d431e207991eb3b29d8',
    messagingSenderId: '936437867273',
    projectId: 'skillmatch-8a9c0',
    databaseURL: 'https://skillmatch-8a9c0-default-rtdb.firebaseio.com',
    storageBucket: 'skillmatch-8a9c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknvKhAz1nnjB8VRP8rZT96eBqimoQRZs',
    appId: '1:936437867273:ios:92f90a27acb9cb4c3b29d8',
    messagingSenderId: '936437867273',
    projectId: 'skillmatch-8a9c0',
    databaseURL: 'https://skillmatch-8a9c0-default-rtdb.firebaseio.com',
    storageBucket: 'skillmatch-8a9c0.firebasestorage.app',
    iosBundleId: 'com.example.skilmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknvKhAz1nnjB8VRP8rZT96eBqimoQRZs',
    appId: '1:936437867273:ios:92f90a27acb9cb4c3b29d8',
    messagingSenderId: '936437867273',
    projectId: 'skillmatch-8a9c0',
    databaseURL: 'https://skillmatch-8a9c0-default-rtdb.firebaseio.com',
    storageBucket: 'skillmatch-8a9c0.firebasestorage.app',
    iosBundleId: 'com.example.skilmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRmJBir_Bkod0JGqhkJYws6a4OUt4G1nc',
    appId: '1:936437867273:web:706be40465bd3f6a3b29d8',
    messagingSenderId: '936437867273',
    projectId: 'skillmatch-8a9c0',
    authDomain: 'skillmatch-8a9c0.firebaseapp.com',
    databaseURL: 'https://skillmatch-8a9c0-default-rtdb.firebaseio.com',
    storageBucket: 'skillmatch-8a9c0.firebasestorage.app',
    measurementId: 'G-75FLE4DVHZ',
  );

}